# Generated by Django 4.2.4 on 2023-09-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=255)),
                ("born_date", models.DateField()),
                ("born_location", models.CharField(max_length=255)),
                ("biography", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
