# Generated by Django 4.2.4 on 2023-09-03 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0004_tag_quote_tag_tag"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tag",
            name="tag",
        ),
    ]
