# Generated by Django 4.2.4 on 2023-09-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0006_alter_tag_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
