# Generated by Django 4.2.4 on 2023-09-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0007_tag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.SlugField(
                default=models.CharField(max_length=255), unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                default=models.CharField(max_length=64, unique=True), unique=True
            ),
        ),
    ]
