# Generated by Django 4.2.4 on 2023-09-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0008_author_slug_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
