# Generated by Django 4.2.4 on 2023-09-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0012_remove_author_slug_alter_tag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.SlugField(
                default=models.CharField(max_length=255), unique=True
            ),
        ),
    ]
