# Generated by Django 4.2.4 on 2023-09-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0013_author_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=models.SlugField(default="fullname", unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(default="tag", unique=True),
        ),
    ]
