# Generated by Django 4.2.4 on 2023-09-05 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0015_alter_author_slug_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("tag",)},
        ),
    ]
