# Generated by Django 4.2.4 on 2023-09-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0016_alter_tag_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
